[package]
name = "svbump"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/tigpt/svbump"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
